* keepass-auth-source for emacs
** Introduction
   This provides KeePass as an auth-source for emacs.
** Requirements
   The following packages are required for keepass-auth-soucre:
   - dash.el
   - s.el


   The following programmes are required to be on your path:

   - [[https://keepass.info/][KeePass]]
   - [[https://keepass.info/plugins.html#kpscript][KPScript]]
** Installation
   Add keepass-auth-source to your =load-path=.
** Setup
   1. Add =(require 'keepass-auth-source)= to your init file
   2. Add =(keepass-auth-source-enable)= to your init file to enable using KeePass database files as an auth-source
** Configuration
   If your KeePass database, called =passwords.kdbx=, is in your .emacs.d directory you should add the following to your init file:

   #+BEGIN_SRC elisp
     (add-to-list 'auth-sources "~/.emacs.d/passwords.kdbx")
   #+END_SRC

   The auth-source will ask for password for the kdbx file when trying to use it as an auth source.

   KeePass database passwords are set to expire after two hours, this can be customized by setting =keepass-auth-source-cache-expiry= to any other value. It can also be customized via =m-x= =customize-variable=.

** Asynchronous Operation
   By default, keepass-auth-source uses synchronous calls to KPScript which may block Emacs during database access. For better responsiveness, especially with slow network connections or large databases, you can enable asynchronous operation:

   #+BEGIN_SRC elisp
     (setq keepass-auth-source-async t)
   #+END_SRC

   When enabled, KPScript is invoked using =make-process= instead of synchronous =call-process=. This allows Emacs to remain responsive while KeePass database queries are processed in the background.

   *Note:* Asynchronous mode may not be compatible with all auth-source consumers that expect immediate results. Use with caution and test thoroughly with your specific configuration.
